name: Application Test

on:
  push:
    branches:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup env
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env
    - name: Setup client secrest for Google
      run: |
        echo "${{ secrets.CLIENT_SECRET }}" > client_secret.json
    - name: Build docker
      run: |
        docker-compose up -d --build
    - name: Run tests
      run: |
        echo --- Running test cases ---
        docker-compose -f docker-compose.yaml run web pytest
        echo --- Completed test cases ---
